/**
 * Execution context passed to every assertion.
 */
export interface AssertionContext {
  /** Absolute path of the root directory. */
  root: string;
  /** Subject path as declared in the manifest. */
  subjectPath: string;
  /** Absolute path resolved from root and subjectPath. */
  absolutePath: string;
}

export type AssertionOutcome = { ok: true } | { ok: false; message: string };

/** Runs a single assertion against a resolved subject path. */
export type AssertionExecutor = (context: AssertionContext) => Promise<AssertionOutcome>;

/**
 * Builds an executor from manifest-provided arguments.
 * Throws AssertionArgumentError when the arguments are invalid.
 */
export type AssertionBuilder = (args: unknown) => AssertionExecutor;

/**
 * A supported assertion: its manifest name, its documentation, and how
 * to build an executor from arguments.
 *
 * The `doc` field is the single source of truth for docs/assertions.md,
 * which is generated by `npm run gen:docs`. Keep it as Markdown, without
 * a leading `## <name>` heading (the generator adds it).
 */
export interface AssertionDefinition {
  name: string;
  doc: string;
  build: AssertionBuilder;
}

/** A validated assertion, ready to execute against a subject path. */
export interface AssertionSpec {
  name: string;
  execute: AssertionExecutor;
}

export class AssertionArgumentError extends Error {}

/**
 * Helper for assertions that take no arguments (string form only).
 */
export function requireNoArgs(name: string, args: unknown): void {
  if (args !== undefined) {
    throw new AssertionArgumentError(`"${name}" does not take arguments`);
  }
}
